### PR TITLE
added bucket sort file

### PR DESCRIPTION
**Pull request by HIMANSHU3107**

### CODE REVIEW

**Comment by ekdnam** [comment]
Can you take input for the array from the user? 

Also mention the issue you are solving in the description of the PR. It makes handling everything really easy for me

**Comment by HIMANSHU3107** [comment]
Sure

**Comment by HIMANSHU3107** [comment]
I have committed the changes, as asked by you.

**Comment by ekdnam** [comment]
LGTM! Merging into master. Thanks for the contribution!

**Pull request merged**
