### PR TITLE
Added the code of bellman ford algorithm in C++

### PR DESCRIPTION
**Pull request by itsarjun12**
#26 Bellman Ford Algorithm | Graph | C++ ( added code of bellman ford algorithm)
i have added the code of bellman ford algorithm.
please look at @ekdnam

### CODE REVIEW

**Comment by ekdnam** [comment]
I cannot understand what are the changes you have made. What are you trying to do?

While committing, please make sure that the description is up to date, and correctly tells about what the change is trying to achieve.

**Comment by itsarjun12** [comment]
> I cannot understand what are the changes you have made. What are you trying to do?
> 
> While committing, please make sure that the description is up to date, and correctly tells about what the change is trying to achieve.

i sent you a one pull request where i have added the code of linear search in c++ and after that i picked a issue of bellman ford code in c++ where i added the code of bellman ford and i sent request again and it adds up with one so here you can say that i have solved two issues in one request.

**Comment by itsarjun12** [comment]
please merge this @ekdnam

**Comment by itsarjun12** [comment]
if you say i can remove linear search code then u can merge my bellman ford algorithm code.

**Comment by itsarjun12** [comment]
i have added the bellman ford code and linear search code.
now u clear or not. if you are not then please let me know.

**Comment by itsarjun12** [comment]
i have clearly mentioned issue number.

**Comment by itsarjun12** [comment]
> #26 Bellman Ford Algorithm | Graph | C++ ( added code of bellman ford algorithm)
> please look at @ekdnam

**Comment by itsarjun12** [comment]
now you will be clear.
i hope

**Comment by itsarjun12** [comment]
this is about issue #26 please look  at my code.

**Comment by ekdnam** [comment]
Be patient. I can't constantly look at PRs.

**Comment by ekdnam** [comment]
Merging into master

**Comment by itsarjun12** [comment]
> Be patient. I can't constantly look at PRs.

ok, I will keep this in mind next time and thank u so much @ekdnam. 😊🤩

**Pull request merged**
