### PR TITLE
A-star algo.

### PR DESCRIPTION
**Pull request by Nivya-21**
A star algorithm added, with proper comments.

### CODE REVIEW

**Comment by ekdnam** [comment]
I have made some changes. Merging into master. Thanks for the contribution!

**Comment by Nivya-21** [comment]
Hey! The PR is showing ineligible for Hacktober - showing 
**Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.**
So can you kindly see to it, thanks .

**Comment by ekdnam** [comment]
I have added the label. Is the repo eligible now?

**Comment by Nivya-21** [comment]
Yes now it's eligible, thanks mate!

**Pull request merged**
