### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rajatpanchotia**
i have added in Readme.md file for linear search

### CODE REVIEW

**Comment by ekdnam** [comment]
LGTM! 

Also add the time complexity of the algorithm if you haven't, then I'll merge it

**Comment by rajatpanchotia** [comment]
> LGTM!
> 
> Also add the time complexity of the algorithm if you haven't, then I'll merge it

I have updated it thanks

**Comment by ekdnam** [comment]
Do prettify the README using MD Syntax. Like `#`,  `##`

**Comment by rajatpanchotia** [comment]
> Do prettify the README using MD Syntax. Like `#`, `##`

ok

**Comment by ekdnam** [comment]
Another PR has resolved this issue :( 

If you want, you can add to that README, or solve any of our issues

**Pull request closed without merging**
