### PR TITLE
DFS Algorithm

### PR DESCRIPTION
**Pull request by Manas502**
Contains algorithm for DFS

### CODE REVIEW

**Comment by ekdnam** [comment]
The file should have the file extension .cpp / .cc

**Comment by ekdnam** [comment]
If you want, delete this file and create a new file with the specifications (filename = DFS.cpp) and I'll merge it!

**Comment by Manas502** [comment]
sure

**Comment by Manas502** [comment]
[DFS Traversal.zip](https://github.com/ekdnam/Algorithms/files/5321768/DFS.Traversal.zip)

**Comment by Manas502** [comment]
I have uploaded a zip file containing the cpp file. Is it feasible or should I close this and send a new pull request?

**Comment by ekdnam** [comment]
Zip files cannot be merged here. As I mentioned above, you can do the same if you want

**Pull request closed without merging**
