### PR TITLE
Adding Bellman Ford Shortest Path Algorithm

### PR DESCRIPTION
**Pull request by bansalmohitwss**

### CODE REVIEW

**Comment by ekdnam** [comment]
There is a stray bracket at the beginning of the file. Remove it, I'll merge then!

**Comment by bansalmohitwss** [comment]
I have removed that bracket. You can merge now.

**Comment by ekdnam** [comment]
LGTM! Thanks for the contribution! Merging into master

**Comment by bansalmohitwss** [comment]
This repository is showing as "Ineligible repository" at Hacktoberfest.

**Pull request merged**
