### PR TITLE
Bubble sort python

### PR DESCRIPTION
**Pull request by ankurjain00**
Add bubble sort (python)
Issue #41
FileName BubbleSort.py

### CODE REVIEW

**Comment by ekdnam** [comment]
Seems correct! The branch needs to be rebased with the python branch here, otherwise a lot of different and unwanted changes can happen. Can you once do that?

**Comment by ankurjain00** [comment]
> Seems correct! The branch needs to be rebased with the python branch here, otherwise a lot of different and unwanted changes can happen. Can you once do that?

sure

**Comment by ankurjain00** [comment]
done

**Comment by ankurjain00** [comment]
> > Seems correct! The branch needs to be rebased with the python branch here, otherwise a lot of different and unwanted changes can happen. Can you once do that?
> 
> sure

rebase done

**Comment by ekdnam** [comment]
The original branch seems to have been based off the master branch, which is C++ implementations. 

My suggestions:
- Create a new branch in your repo, based on the current python branch of ekdnam\algorithms.
- Here, add bubblesort.py (what you have done currently here) in the reqd directory.
- Create a new PR to the ekdnam:python branch.
- Done!

**Pull request closed without merging**
