### PR TITLE
Create fibonnaci search.c

### PR DESCRIPTION
**Pull request by avnishsingh516**

### CODE REVIEW

**Comment by ekdnam** [comment]
LGTM!

Two things
- Rename the file to fibonacciSearch.c
- Rename the function to fibonaccISearch()

GFG has fibMonacci, but here we want fibonacci 😄

**Comment by avnishsingh516** [comment]
i changed the function name and file name

**Comment by avnishsingh516** [comment]
final changes. i made the input dynamic and changes the file and function name also.
Please, review

**Comment by ekdnam** [comment]
LGTM! Thanks for your contribution! Merging into master

**Pull request merged**
