### PR TITLE
Add Insertion Sort

### PR DESCRIPTION
**Pull request by PritiShaw**
The PR creates a file insertionSort.c in Sorting/Insertion Sort.

### CODE REVIEW

**Comment by ekdnam** [comment]
Why are you not following the template for a PR? Why are you deleting the template?

**Comment by ekdnam** [comment]
The template has been created for a purpose.

**Comment by PritiShaw** [comment]
Sorry, I will create a new PR with the Proper template. Any other changes apart from the template?
Thanks

**Comment by ekdnam** [comment]
From the outset it seems that you are pushing c code from your branch which has c++ code, into ekdam:master, which cannot be allowed. You have to make a new PR, with this code in your c branch, and the PR to the ekdam:c.

**Comment by ekdnam** [comment]
By following the format in the template you check this.

**Pull request closed without merging**
