### PR TITLE
Create linearSearchAlgorithm.cpp

### PR DESCRIPTION
**Pull request by anantbharti**

### CODE REVIEW

**Comment by ekdnam** [comment]
LGTM! Just take input from the user dynamically, rather than declaring a static array, and then I will merge it!

Also add description for your PR

**Comment by anantbharti** [comment]
Task done! Please ask if any more changes required, else merge it.

**Comment by ekdnam** [comment]
I made the changes. Well done! Merging it into master

**Comment by anantbharti** [comment]
Thanks a lot!

**Comment by anantbharti** [comment]
Hey @ekdnam ! Can you please hacktoberfest-accepted label as I am participating in Hacktoberfest2020

**Comment by anantbharti** [comment]
@ekdnam Thanks a lot !

**Comment by ekdnam** [comment]
@anantbharti Sure! Is it working now?

**Pull request merged**
