### PR TITLE
Create Fibonacci Search.cpp

### PR DESCRIPTION
**Pull request by cuber485**
file location=> Searching/Fibonacci Search

### CODE REVIEW

**Comment by ekdnam** [comment]
This is the code for Fibonacci Series, not Fibonacci Search

**Comment by cuber485** [comment]
@ekdnam  Sorry about that. Please check it now.

**Comment by ekdnam** [comment]
Rename the file to `fibonacciSearch.cpp` and the function to `fibonacciSearch`

**Comment by cuber485** [comment]
@ekdnam  Is it ok?

**Comment by ekdnam** [comment]
Okay sure! Thanks for the contribution! merging into master.

**Comment by cuber485** [comment]
Happy to contribute

**Pull request merged**
