### PR TITLE
Added BFS in C++

### PR DESCRIPTION
**Pull request by itsarjun12**
## Description ##
This PR adds the bFS.c++ file to /Graph Theory/BFS in the petch-2 branch.
## If it is solving an issue, mention the issue number
issue number - #2 

## Language ##
(enter x where it is correct for you)
- [] C
- [x] C++
- [] Java
- [] Python

## Language - Branch mapping
| Lang      | The branch to which you are making the PR|
| C++   | master        |

## Does your PR satisfy this mapping?
- [x] Yes
- [] No

### Essentials ###
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] Code is well-documented

### Changes ###
- [x] Addition of code of BFS graph algorithm code in C++

### CODE REVIEW

**Comment by itsarjun12** [comment]
@ekdnam, I think, you should visit my PR because I did this four hours ago and my one request still you did not merge that i committed yesterday.

**Comment by itsarjun12** [comment]
i think it's too much time.

**Comment by ekdnam** [comment]
Be patient. Currently I am busy with something else due to which I can't pay attention to the notifications for this repo. If you think it is too much time, you can contribute to other repos as well.

**Comment by itsarjun12** [comment]
Thank you !!

**Pull request merged**
